### ISSUE TITLE
Submit zhCN Client no PopupDialogs

### ISSUE THREAD

**Issue by Qcat0214** [Road-block/MasterLootRemind#1]
hey road-block.I localize your Addon
But there is no PopupDialogs in the zhCN client :(
Business as usual in English client

**Comment by Road-block** [comment]
This is going to be hard to debug with me not having access to an eastern language client.  
If you can find someone to test this chat command on one of the NPCs in [Babble-Boss-2.2](https://github.com/Road-block/MasterLootRemind/blob/master/libs/Babble-Boss-2.2/Babble-Boss-2.2.lua) that's easy to get to, it would be a start.  

For example https://classicdb.ch/?npc=3100

Target it and run the following command, see what it prints.

```lua
/run local b=AceLibrary("Babble-Boss-2.2")DEFAULT_CHAT_FRAME:AddMessage(tostring(b:HasTranslation(UnitName("target"))))
```

**Comment by Road-block** [comment]
Oh, it would also help if I had the localized addon, to see what you've done ;)

**Comment by Qcat0214** [comment]
I tested the macros you gave.And added a test mob "Winter Wolf" to Babble-Boss-2.2.
But it's a display of "nil" in chatframe
This is my localised addon Download links: https://pan.baidu.com/s/1ghlendT

**Comment by Road-block** [comment]
I'll check it later, that's helpful. I imagined it was something like that.  
Babble-Boss-2.2 (and all Ace libraries) only 1 instance remains loaded in game.  
To be sure your test was good, you either need to edit all Babble-Boss-2.2 instances in your AddOns folder or make sure you load in with only 1 for the test.

**Comment by Qcat0214** [comment]
ok.I did what you said.Reedit the Babble-Boss-2.2
as follows:

BabbleBoss:RegisterTranslations("enUS", function()
	return {

        ["Winter Wolf"] = true,
	}
end)


BabbleBoss:RegisterTranslations("zhCN", function()
	return {

        ["Winter Wolf"] = "冬狼",
	}
end)

--------------------------------------------------------------------------------------------
Still can't PopupDialogs .Is it the other problem of Ace2 libraries?

**Comment by Qcat0214** [comment]
I just edited it once more.
in Babble-Boss-2.2:
BabbleBoss:RegisterTranslations("zhCN", function()
	return {

        ["冬狼"] = true,
	}
end)

And I have to delete the enUS part of the Babble-Boss-2.2. So the editors can popup. addon can work properly.This is why?

**Comment by Road-block** [comment]
That's quite strange.  
Does `/print GetLocale()` on Chinese client not return "zhCN"?  
Ace2 should load the proper locale, but it's good you found workaround, we'll figure it out.

**Comment by Road-block** [comment]
Can you try the latest alpha version from [master](https://github.com/Road-block/MasterLootRemind/archive/master.zip)? (remove -master suffix from folder)  
Without removing the enUS terms from Babble-Boss-2.2 and see if that works better.

**Comment by Qcat0214** [comment]
I tested your latest version.
I didn't do any editors.But it's a pity that it's the same as before

**Comment by Qcat0214** [comment]
oh.
I was wrong
He worked :D

**Comment by Road-block** [comment]
Alright, I'll package a release shortly.  
Thanks for the assist.

**Comment by Qcat0214** [comment]
in addition.Give you a copy of the zhCN I have re - translated
Specializes in the Light's Hope server

BabbleBoss:RegisterTranslations("zhCN", function()
	return {
		["Avalanchion"] = "阿瓦兰奇奥",
		["The Windreaver"] = "烈风掠夺者",
		["Baron Charr"] = "火焰男爵查尔",
		["Princess Tempestria"] = "泰比斯蒂亚公主",
		["Grethok the Controller"] = "黑翼控制者",
		["Patchwerk"] = "帕奇维克",
		["Grobbulus"] = "葛罗巴斯",
		["Gluth"] = "古鲁斯",
		["Feugen"] = "伏晨",
		["Stalagg"] = "斯塔拉格",
		["Thaddius"] = "泰迪斯",
		["Anub'Rekhan"] = "阿努布雷坎",
		["Grand Widow Faerlina"] = "黑女巫法琳娜",
		["Maexxna"] = "梅克丝娜",
		["Instructor Razuvious"] = "教官拉苏维奥斯",
		["Deathknight Understudy"] = "死亡骑士复仇者",
		["Gothik the Harvester"] = "收割者戈提克",
		["Highlord Mograine"] = "大领主莫格莱尼",
		["Thane Korth'azz"] = "库尔塔兹领主",
		["Lady Blaumeux"] = "女公爵布洛莫斯",
		["Sir Zeliek"] = "札里克爵士",
		["The Four Horsemen"] = "四骑士的宝箱",
		["Noth the Plaguebringer"] = "瘟疫者诺斯",
		["Heigan the Unclean"] = "肮脏者海根",
		["Loatheb"] = "憎恨者",
		["Sapphiron"] = "萨菲隆",
		["Kel'Thuzad"] = "克尔苏加德",
		["Lord Victor Nefarius"] = "维克多·奈法里奥斯",
		["Nefarian"] = "奈法利安",
		["Vaelastrasz the Corrupt"] = "堕落的瓦拉斯塔兹",
		["Razorgore the Untamed"] = "狂野的拉佐格尔",
		["Broodlord Lashlayer"] = "勒西雷尔",
		["Chromaggus"] = "克洛玛古斯",
		["Ebonroc"] = "埃博诺克",
		["Firemaw"] = "费尔默",
		["Flamegor"] = "弗莱格尔",
		["Majordomo Executus"] = "管理者埃克索图斯",
		["Ragnaros"] = "拉格纳罗斯",
		["Baron Geddon"] = "迦顿男爵",
		["Golemagg the Incinerator"] = "焚化者古雷曼格",
		["Garr"] = "加尔",
		["Sulfuron Harbinger"] = "萨弗隆先驱者",
		["Shazzrah"] = "沙斯拉尔",
		["Lucifron"] = "鲁西弗隆",
		["Gehennas"] = "基赫纳斯",
		["Magmadar"] = "玛格曼达",
		["Onyxia"] = "奥妮克希亚",
		["Azuregos"] = "艾索雷葛斯",
		["Lord Kazzak"] = "卡扎克",
		["Ysondre"] = "伊索德雷",
		["Emeriss"] = "艾莫莉丝",
		["Taerar"] = "泰拉尔",
		["Lethon"] = "雷索",
		["High Priestess Jeklik"] = "高阶祭司耶克里克",
		["High Priest Venoxis"] = "高阶祭司温诺希斯",
		["High Priest Thekal"] = "High Priest Thekal",
		["High Priestess Arlokk"] = "哈卡莱先知",
		["High Priestess Mar'li"] = "哈卡莱安魂者",
		["Jin'do the Hexxer"] = "妖术师金度",
		["Bloodlord Mandokir"] = "血领主曼多基尔",
		["Gahz'ranka"] = "加兹兰卡",
		["Gri'lek"] = "格里雷克",
		["Hazza'rah"] = "哈札拉尔",
		["Renataki"] = "雷纳塔基",
		["Wushoolay"] = "乌苏雷",
		["Hakkar"] = "哈卡",
		["Ayamiss the Hunter"] = "狩猎者阿亚米斯",
		["Buru the Gorger"] = "吞咽者布鲁",
		["General Rajaxx"] = "拉贾克斯将军",
		["Lieutenant General Andorov"] = "安多洛夫中将",
		["Moam"] = "莫阿姆",
		["Anubisath Guardian"] = "阿努比萨斯守卫者",
		["Ossirian the Unscarred"] = "无疤者奥斯里安",
		["Lord Kri"] = "克里勋爵",
		["Princess Yauj"] = "亚尔基公主",
		["Vem"] = "维姆",
		["The Bug Family"] = "虫子一家",
		["Eye of C'Thun"] = "克苏恩之眼",
		["C'Thun"] = "克苏恩",
		["Anubisath Defender"] = "阿努比萨斯防御者",
		["Anubisath Warder"] = "阿努比萨斯守卫",
		["Fankriss the Unyielding"] = "顽强的范克瑞斯",
		["Princess Huhuran"] = "哈霍兰公主",
		["Ouro"] = "奥罗",
		["Battleguard Sartura"] = "沙尔图拉",
		["The Prophet Skeram"] = "预言者斯克拉姆",
		["Emperor Vek'lor"] = "维克洛尔大帝",
		["Emperor Vek'nilash"] = "维克尼拉斯大帝",
		["The Twin Emperors"] = "双子皇帝",
		["Viscidus"] = "维希度斯",
		["Alzzin the Wildshaper"] = "奥兹恩",
		["Ambassador Flamelash"] = "弗莱拉斯大使",
		["Anger'rel"] = "安格雷尔",
		["Archivist Galford"] = "档案管理员加尔福特",
		["Atal'alarion"] = "阿塔拉利恩",
		["Avatar of Hakkar"] = "哈卡的化身",
		["Bael'Gar"] = "贝尔加",
		["Balnazzar"] = "巴纳札尔",
		["Baroness Anastari"] = "安娜丝塔丽男爵夫人",
		["Baron Rivendare"] = "瑞文戴尔男爵",
		["Cannon Master Willey"] = "炮手威利",
		["Captain Kromcrush"] = "克罗卡斯",
		["Celebras the Cursed"] = "被诅咒的塞雷布拉斯",
		["Crystal Fang"] = "水晶之牙",
		["Darkmaster Gandling"] = "通灵院长·加丁",
		["Doctor Theolen Krastinov"] = "瑟尔林·卡斯迪诺夫教授",
		["Doom'rel"] = "杜姆雷尔",
		["Dope'rel"] = "多普雷尔",
		["Dreamscythe"] = "德姆塞卡尔",
		["Emperor Dagran Thaurissan"] = "达格兰·索瑞森大帝",
		["Fineous Darkvire"] = "弗诺斯·达克维尔",
		["Gasher"] = "加什尔",
		["General Angerforge"] = "安格弗将军",
		["General Drakkisath"] = "达基萨斯将军",
		["Gloom'rel"] = "格鲁雷尔",
		["Golem Lord Argelmach"] = "傀儡统帅阿格曼奇",
		["Goraluk Anvilcrack"] = "古拉鲁克",
		["Guard Fengus"] = "卫兵芬古斯",
		["Guard Mol'dar"] = "卫兵摩尔达",
		["Guard Slip'kik"] = "卫兵斯里基克",
		["Gyth"] = "盖斯",
		["Halycon"] = "哈雷肯",
		["Hate'rel"] = "黑特雷尔",
		["Hazzas"] = "哈札斯",
		["Hearthsinger Forresten"] = "弗雷斯特恩",
		["The Unforgiven"] = "不可宽恕者";
		["High Interrogator Gerstahn"] = "审讯官格斯塔恩",
		["Highlord Omokk"] = "欧莫克大王",
		["Hukku"] = "胡库",
		["Hurley Blackbreath"] = "霍尔雷·黑须",
		["Hydrospawn"] = "海多斯博恩",
		["Illyanna Ravenoak"] = "伊琳娜·暗木",
		["Immol'thar"] = "伊莫塔尔",
		["Instructor Malicia"] = "讲师玛丽希亚",
		["Jammal'an the Prophet"] = "预言者迦玛兰",
		["Jandice Barov"] = "詹迪斯·巴罗夫",
		["King Gordok"] = "戈多克大王",
		["Kirtonos the Herald"] = "传令官基尔图诺斯",
		["Lady Illucia Barov"] = "伊露希亚·巴罗夫",
		["Landslide"] = "兰斯利德",
		["Lethtendris"] = "蕾瑟塔蒂丝",
		["Lord Alexei Barov"] = "阿雷克斯·巴罗夫",
		["Lord Incendius"] = "伊森迪奥斯",
		["Lord Vyletongue"] = "维利塔恩",
		["Lorekeeper Polkelt"] = "博学者普克尔特",
		["Loro"] = "洛若尔",
		["Magister Kalendris"] = "卡雷迪斯镇长",
		["Magistrate Barthilas"] = "巴瑟拉斯镇长",
		["Magmus"] = "玛格姆斯",
		["Maleki the Pallid"] = "苍白的玛勒基",
		["Marduk Blackpool"] = "马杜克·布莱克波尔",
		["Meshlok the Harvester"] = "收割者麦什洛克",
		["Mijan"] = "米杉",
		["Morphaz"] = "摩弗拉斯",
		["Mother Smolderweb"] = "烟网蛛后",
		["Nerub'enkan"] = "奈鲁布恩坎",
		["Noxxion"] = "诺克赛恩",
		["Ogom the Wretched"] = "可悲的奥戈姆",
		["Overlord Wyrmthalak"] = "维姆萨拉克",
		["Phalanx"] = "法拉克斯",
		["Plugger Spazzring"] = "普拉格",
		["Postmaster Malown"] = "邮差玛罗恩",
		["Princess Moira Bronzebeard"] = "铁炉堡公主茉艾拉·铜须",
		["Princess Theradras"] = "瑟莱德丝公主",
		["Prince Tortheldrin"] = "托塞德林王子",
		["Pusillin"] = "普希林",
		["Pyroguard Emberseer"] = "烈焰卫士艾博希尔",
		["Ramstein the Gorger"] = "吞咽者拉姆斯登",
		["Ras Frostwhisper"] = "莱斯·霜语",
		["Rattlegore"] = "血骨傀儡",
		["Razorlash"] = "锐刺鞭笞者",
		["Warchief Rend Blackhand"] = "大酋长雷德·黑手",
		["Ribbly Screwspigot"] = "雷布里·斯库比格特",
		["Rotgrip"] = "洛特格里普",
		["Seeth'rel"] = "西斯雷尔",
		["Shade of Eranikus"] = "伊兰尼库斯的阴影",
		["Shadow Hunter Vosh'gajin"] = "暗影猎手沃许加斯",
		["Solakar Flamewreath"] = "索拉卡·火冠",
		["Stomper Kreeg"] = "践踏者克雷格",
		["Tendris Warpwood"] = "特迪斯·扭木",
		["The Beast"] = "比斯巨兽",
		["The Ravenian"] = "拉文尼亚",
		["Timmy the Cruel"] = "悲惨的提米",
		["Tinkerer Gizlock"] = "工匠吉兹洛克",
		["Tsu'zee"] = "苏斯",
		["Vectus"] = "维克图斯",
		["Vile'rel"] = "瓦勒雷尔",
		["War Master Voone"] = "指挥官沃恩",
		["Weaver"] = "德拉维沃尔",
		["Zevrim Thornhoof"] = "瑟雷姆·刺蹄",
		["Zolo"] = "祖罗",
		["Zul'Lor"] = "祖罗尔",
		
		-- From Mendeleev
		["Cho'Rush the Observer"] = "观察者克鲁什",
		["Lord Hel'nurath"] = "赫尔努拉斯",
		["Pimgib"] = "匹姆吉布",
		["Knot Thimblejack's Cache"] = "诺特·希姆加克的储物箱",
		["Cannonmaster Willey"] = "炮手威利",
		["Emperor Dagran Thaurissian"] = "达格兰·索瑞森大帝",
		["Archmage Arugal"] = "大法师阿鲁高",
		["Archmage Arugal's Voidwalker"] = "阿鲁高的虚空行者",
		["Baron Silverlaine"] = "席瓦莱恩男爵",
		["Commander Springvale"] = "指挥官斯普林瓦尔",
		["Deathsworn Captain"] = "死亡之誓队长",
		["Fenrus the Devourer"] = "吞噬者芬鲁斯",
		["Odo the Blindwatcher"] = "盲眼守卫奥杜",
		["Razorclaw the Butcher"] = "屠夫拉佐克劳",
		["Wolf Master Nandos"] = "狼王南杜斯",
		["Rend Blackhand"] = "大酋长雷德·黑手",
		["Kurinnaxx"] = "库林纳克斯",
            
		["Maur Grimtotem"] = "玛尔·恐怖图腾",
		["Oggleflint"] = "奥格弗林特",
		["Taragaman the Hungerer"] = "饥饿者塔拉加曼",
		["Jergosh the Invoker"] = "祈求者耶戈什",
		["Bazzalan"] = "巴札兰",
		["Disciple of Naralex"] = "纳拉雷克斯的信徒",
		["Lord Cobrahn"] = "考布莱恩",
		["Lady Anacondra"] = "安娜科德拉",
		["Kresh"] = "克雷什",
		["Lord Pythas"] = "皮萨斯",
		["Skum"] = "斯卡姆",
		["Lord Serpentis"] = "瑟芬迪斯",
		["Verdan the Everliving"] = "永生者沃尔丹",
		["Mutanus the Devourer"] = "吞噬者穆坦努斯",
		["Naralex"] = "纳拉雷克斯",
		["Deviate Faerie Dragon"] = "变异精灵龙",
		["Ghamoo-ra"] = "加摩拉",
		["Lady Sarevess"] = "萨利维丝",
		["Gelihast"] = "格里哈斯特",
		["Lorgus Jett"] = "洛古斯·杰特",
		["Baron Aquanis"] = "阿奎尼斯男爵",
		["Twilight Lord Kelris"] = "梦游者克尔里斯",
		["Old Serra'kis"] = "瑟拉吉斯",
		["Aku'mai"] = "阿库麦尔",
		["Roogug"] = "鲁古格",
		["Aggem Thorncurse"] = "阿格姆",
		["Death Speaker Jargba"] = "亡语者贾格巴",
		["Overlord Ramtusk"] = "主宰拉姆塔斯",
		["Agathelos the Raging"] = "暴怒的阿迦赛罗斯",
		["Blind Hunter"] = "盲眼猎手",
		["Charlga Razorflank"] = "卡尔加·刺肋",
		["Earthcaller Halmgar"] = "唤地者哈穆加",
		["Tuten'kash"] = "图特卡什",
		["Lady Falther'ess"] = "Lady Falther'ess",
		["Mordresh Fire Eye"] = "火眼莫德雷斯",
		["Glutton"] = "暴食者",
		["Ragglesnout"] = "拉戈斯诺特",
		["Amnennar the Coldbringer"] = "寒冰之王亚门纳尔",
		["Plaguemaw the Rotting"] = "腐烂的普雷莫尔",
		["Antu'sul"] = "安图苏尔",
		["Witch Doctor Zum'rah"] = "巫医祖穆拉恩",
		["Shadowpriest Sezz'ziz"] = "暗影祭司塞瑟斯",
		["Gahz'rilla"] = "Gahz'rilla",
		["Chief Ukorz Sandscalp"] = "乌克兹·沙顶",
		["Ruuzlu"] = "卢兹鲁",
		["Isalien"] = "依萨利恩",
		["Revanchion"] = "Revanchion",
		["Lord Roccor"] = "洛考尔",
		["Anub'shiah"] = "阿努希尔",
		["Eviscerator"] = "剜眼者",
		["Gorosh the Dervish"] = "修行者高罗什",
		["Grizzle"] = "格里兹尔",
		["Hedrum the Creeper"] = "爬行者赫杜姆",
		["Ok'thor the Breaker"] = "破坏者奥科索尔",
		["Houndmaster Grebmar"] = "驯犬者格雷布玛尔",
		["Pyromancer Loregrain"] = "控火师罗格雷恩",
		["Warder Stilgiss"] = "典狱官斯迪尔基斯",
		["Verek"] = "维雷克",
		["Watchman Doomgrip"] = "卫兵杜格瑞普",
		["Panzor the Invincible"] = "无敌的潘佐尔",
		["Mor Grayhoof"] = "莫尔·灰蹄",
		["Bannok Grimaxe"] = "班诺克·巨斧",
		["Urok Doomhowl"] = "乌洛克",
		["Quartermaster Zigris"] = "军需官兹格雷斯",
		["Gizrul the Slavener"] = "奴役者基兹卢尔",
		["Ghok Bashguud"] = "霍克·巴什古德",
		["Jed Runewatcher"] = "杰德";
		["Lord Valthalak"] = "瓦萨拉克";
		["Grubbis"] = "格鲁比斯";
		["Chomper"] = "咀嚼者";
		["Viscous Fallout"] = "粘性辐射尘";
		["Electrocutioner 6000"] = "电刑器6000型";
		["Crowd Pummeler 9-60"] = "群体打击者9-60";
		["Dark Iron Ambassador"] = "黑铁大师";
		["Mekgineer Thermaplugg"] = "麦克尼尔·瑟玛普拉格";
		["Houndmaster Loksey"] = "驯犬者洛克希";
		["Arcanist Doan"] = "秘法师杜安";
		["Herod"] = "赫洛德";
		["High Inquisitor Fairbanks"] = "大检察官法尔班克斯";
		["Scarlet Commander Mograine"] = "血色十字军指挥官莫格莱尼";
		["High Inquisitor Whitemane"] = "大检察官怀特迈恩";
		["Interrogator Vishas"] = "审讯员韦沙斯";
		["Bloodmage Thalnos"] = "血法师萨尔诺斯";
		["Ironspine"] = "铁脊死灵";
		["Azshir the Sleepless"] = "永醒的艾希尔";
		["Fallen Champion"] = "亡灵勇士";
		["Lord Blackwood"] = "黑木王";
		["Death Knight Darkreaver"] = "死亡骑士达克雷尔";
		["Kormok"] = "库尔莫克";
		["Skul"] = "斯库尔";
		["Balzaphon"] = "巴尔萨冯";
		["Malor the Zealous"] = "狂热的玛洛尔";
		["Sothos"] = "索托斯";
		["Jarien"] = "亚雷恩";
		["Stonespine"] = "石脊";
		["Rhahk'Zor"] = "拉克佐";
		["Miner Johnson"] = "矿工约翰森";
		["Sneed"] = "斯尼德";
		["Gilnid"] = "基尔尼格";
		["Captain Greenskin"] = "绿皮队长";
		["Edwin VanCleef"] = "艾德温·范克里夫";
		["Mr. Smite"] = "重拳先生";
		["Cookie"] = "曲奇";
		["Targorr the Dread"] = "可怕的塔格尔";
		["Kam Deepfury"] = "卡姆·深怒";
		["Hamhock"] = "哈姆霍克";
		["Bazil Thredd"] = "巴基尔·斯瑞德";
		["Dextren Ward"] = "迪克斯特·瓦德";
		["Bruegal Ironknuckle"] = "布鲁戈·艾尔克纳寇";
		["Baelog"] = "巴尔洛戈";
		["Eric \"The Swift\""] = "埃瑞克";
		["Olaf"] = "奥拉夫";
		["Revelosh"] = "鲁维罗什";
		["Ironaya"] = "艾隆纳亚";
		["Obsidian Sentinel"] = "黑曜石哨兵";
		["Ancient Stone Keeper"] = "古代的石头看守者";
		["Galgann Firehammer"] = "加加恩·火锤";
		["Grimlok"] = "格瑞姆洛克";
		["Archaedas"] = "阿扎达斯";
		["Sever"] = "Sever";
		["Scorn"] = "Scorn";
		["Rethilgore"] = "雷希戈尔";
		["Atiesh"] = "埃提耶什";
		["Stratholme Courier"] = "斯坦索姆信使";
		["Ancient Core Hound"] = "上古熔火恶犬";
		["Gurubashi Berserker"] = "古拉巴什狂暴者";
        ["Elder Mottled Boar"] = "老杂斑野猪",
        ["Stoneskin Gargoyle"] = "岩肤石像鬼",
	}
end)

**Comment by Road-block** [comment]
Thanks but there is no central repository for Ace2 addons anymore.  
I have no way to distribute this to all addons that load Babble-Boss-2.2.
